//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountUserRole : Entity
    {
        public long AccountUserId { get; set; }
        public RoleType RoleType { get; set; }
        public Nullable<long> RoleId { get; set; }
    
        public virtual AccountUser AccountUser { get; set; }
        public virtual Role Role { get; set; }
    }
}
