//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountBillingPeriodConfiguration : Entity
    {
        public long AccountBillingPreferenceId { get; set; }
        public Interval Interval { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Day { get; set; }
        public BillingPeriodType Type { get; set; }
        public BillingPeriodRule Rule { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.DateTime ModifiedTimestamp { get; set; }
    
        public virtual AccountBillingPreference AccountBillingPreference { get; set; }
    }
}
