//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountBrandingPreference : Entity
    {
        public string CompanyName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public Nullable<long> StateId { get; set; }
        public Nullable<long> CountryId { get; set; }
        public string PostalZip { get; set; }
        public string SupportEmail { get; set; }
        public string BillingEmail { get; set; }
        public string WebsiteLabel { get; set; }
        public string WebsiteUrl { get; set; }
        public string BillingPhone { get; set; }
        public string SupportPhone { get; set; }
        public string Fax { get; set; }
        public string FromEmail { get; set; }
        public string ReplyToEmail { get; set; }
        public string FromDisplay { get; set; }
        public string ReplyToDisplay { get; set; }
        public string BccEmail { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
        public virtual AccountPreference AccountPreference { get; set; }
    }
}
