//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountPreference : Entity
    {
        public long TimezoneId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual AccountBrandingPreference AccountBrandingPreference { get; set; }
        public virtual AccountInvoicePreference AccountInvoicePreference { get; set; }
        public virtual Timezone Timezone { get; set; }
    }
}
