//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountInvoicePreference : Entity
    {
        public int NextInvoiceNumber { get; set; }
        public string InvoiceSignature { get; set; }
        public bool ShowShippingAddress { get; set; }
        public string InvoiceNote { get; set; }
        public bool RollUpTaxes { get; set; }
        public string PurchaseLabel { get; set; }
        public bool ShowTrackedItemName { get; set; }
        public bool ShowTrackedItemReference { get; set; }
        public bool ShowTrackedItemDescription { get; set; }
    
        public virtual AccountPreference AccountPreference { get; set; }
    }
}
