//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountCurrency : Entity
    {
        public long AccountId { get; set; }
        public long CurrencyId { get; set; }
        public bool IsDefault { get; set; }
        public CurrencyStatus CurrencyStatus { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
