//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountLedgerBalance : Entity
    {
        public decimal AccountsReceivableBalanceDebit { get; set; }
        public decimal CashCollectedDebit { get; set; }
        public decimal UnearnedBalanceDebit { get; set; }
        public decimal EarnedBalanceDebit { get; set; }
        public decimal WriteOffBalanceDebit { get; set; }
        public decimal TaxesPayableBalanceDebit { get; set; }
        public decimal AccountsReceivableBalanceCredit { get; set; }
        public decimal CashCollectedCredit { get; set; }
        public decimal UnearnedBalanceCredit { get; set; }
        public decimal EarnedBalanceCredit { get; set; }
        public long CurrencyId { get; set; }
        public decimal WriteOffBalanceCredit { get; set; }
        public decimal TaxesPayableBalanceCredit { get; set; }
        public decimal DiscountBalanceDebit { get; set; }
        public decimal DiscountBalanceCredit { get; set; }
        public decimal OpeningBalanceDebit { get; set; }
        public decimal OpeningBalanceCredit { get; set; }
        public decimal CreditDebit { get; set; }
        public decimal CreditCredit { get; set; }
        public decimal UnearnedDiscountBalanceDebit { get; set; }
        public decimal UnearnedDiscountBalanceCredit { get; set; }
    }
}
