//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountEmailTemplate : Entity
    {
        public long AccountId { get; set; }
        public string MarkDownBody { get; set; }
        public string MarkDownSubject { get; set; }
        public bool Enabled { get; set; }
        public string FromEmail { get; set; }
        public string ReplyToEmail { get; set; }
        public string FromDisplay { get; set; }
        public string ReplyToDisplay { get; set; }
        public string BccEmail { get; set; }
        public EmailTemplateType Type { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
