//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountCollectionSchedule : Entity
    {
        public long AccountId { get; set; }
        public int Day { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
