//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountSalesTrackingCodeConfiguration : Entity
    {
        public string SalesTrackingCode1Label { get; set; }
        public string SalesTrackingCode2Label { get; set; }
        public string SalesTrackingCode3Label { get; set; }
        public string SalesTrackingCode4Label { get; set; }
        public string SalesTrackingCode5Label { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.DateTime ModifiedTimestamp { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
