//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountBillingStatementPreference : Entity
    {
        public BillingStatementOption Option { get; set; }
        public Nullable<BillingStatementType> Type { get; set; }
        public Nullable<Interval> Interval { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> Month { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
