//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountFeatureConfiguration : Entity
    {
        public System.DateTime CreatedTimestamp { get; set; }
        public System.DateTime ModifiedTimestamp { get; set; }
        public bool SalesforceEnabled { get; set; }
        public bool SalesforceSandboxMode { get; set; }
        public bool NetsuiteEnabled { get; set; }
        public string AvalaraOrganizationCode { get; set; }
        public TaxOption TaxOption { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
