//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountBillingPreference : Entity
    {
        public AccountBillingPreference()
        {
            this.AccountBillingPeriodConfigurations = new HashSet<AccountBillingPeriodConfiguration>();
        }
    
        public bool AutoPostDraftInvoice { get; set; }
        public Nullable<int> AccountGracePeriod { get; set; }
        public Term DefaultTerm { get; set; }
        public bool DefaultAutoCollect { get; set; }
        public decimal CustomerAcquisitionCost { get; set; }
        public bool ShowZeroDollarCharges { get; set; }
        public CustomerServiceStartOption DefaultCustomerServiceStartOption { get; set; }
        public Nullable<RechargeType> RechargeType { get; set; }
        public Nullable<decimal> RechargeThresholdAmount { get; set; }
        public Nullable<decimal> RechargeTargetAmount { get; set; }
        public Nullable<bool> StatusOnThreshold { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<AccountBillingPeriodConfiguration> AccountBillingPeriodConfigurations { get; set; }
    }
}
