//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog : Entity
    {
        public System.DateTime CreatedTimestamp { get; set; }
        public AuditSource AuditSource { get; set; }
        public Nullable<long> UserId { get; set; }
        public string Message { get; set; }
        public Action Action { get; set; }
        public EntityType EntityType { get; set; }
        public long EntityId { get; set; }
    }
}
