//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvalaraLog : Entity
    {
        public long AccountId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public string Input { get; set; }
        public string Output { get; set; }
        public string FailureReason { get; set; }
        public bool Success { get; set; }
        public int CompletedIn { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public bool Committed { get; set; }
        public Nullable<bool> DevMode { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<long> DraftInvoiceId { get; set; }
        public Nullable<long> InvoiceId { get; set; }
        public AvalaraLogType Type { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
