//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingStatement : Entity
    {
        public BillingStatement()
        {
            this.CustomerEmailLogBillingStatement = new HashSet<CustomerEmailLogBillingStatement>();
        }
    
        public long CustomerId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal OpeningBalance { get; set; }
        public decimal ClosingBalance { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<CustomerEmailLogBillingStatement> CustomerEmailLogBillingStatement { get; set; }
    }
}
