//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingPeriodDefinition : Entity
    {
        public BillingPeriodDefinition()
        {
            this.BillingPeriods = new HashSet<BillingPeriod>();
            this.Subscription = new HashSet<Subscription>();
        }
    
        public long CustomerId { get; set; }
        public Interval Interval { get; set; }
        public int NumberOfIntervals { get; set; }
        public Nullable<int> InvoiceDay { get; set; }
        public BillingPeriodType BillingPeriodType { get; set; }
        public Nullable<int> InvoiceMonth { get; set; }
    
        public virtual ICollection<BillingPeriod> BillingPeriods { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Subscription> Subscription { get; set; }
    }
}
