//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    
    public partial class CashReportCSVFull 
    {
        public long Fusebill_ID { get; set; }
        public string Customer_ID { get; set; }
        public string Customer_First_Name { get; set; }
        public string Customer_Last_Name { get; set; }
        public string Customer_Company_Name { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Address_Line1 { get; set; }
        public string Address_Line2 { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string Ref1 { get; set; }
        public string Ref2 { get; set; }
        public string Ref3 { get; set; }
        public string Accounting_Status__applicable_at_effective_date_of_report_ { get; set; }
        public string Status__applicable_at_effective_date_of_report_ { get; set; }
        public Nullable<System.DateTime> Payment_Effective_Date { get; set; }
        public string Payment_Reference { get; set; }
        public long Payment_Transaction_ID { get; set; }
        public string Payment_Source { get; set; }
        public string Payment_Type { get; set; }
        public string Payment_Method_Type { get; set; }
        public string Payment_Method { get; set; }
        public string Gateway { get; set; }
        public string Gateway_Reference { get; set; }
        public string Related_Payment_ID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Currency { get; set; }
        public string SalesTrackingCode1Code { get; set; }
        public string SalesTrackingCode1Name { get; set; }
        public string SalesTrackingCode2Code { get; set; }
        public string SalesTrackingCode2Name { get; set; }
        public string SalesTrackingCode3Code { get; set; }
        public string SalesTrackingCode3Name { get; set; }
        public string SalesTrackingCode4Code { get; set; }
        public string SalesTrackingCode4Name { get; set; }
        public string SalesTrackingCode5Code { get; set; }
        public string SalesTrackingCode5Name { get; set; }
    }
}
