//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    
    public partial class CashReportSummary 
    {
        public string Source { get; set; }
        public string Type { get; set; }
        public string Method { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
