//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    
    public partial class CashReportCSV 
    {
        public long Fusebill_ID { get; set; }
        public string Customer_ID { get; set; }
        public string Customer_First_Name { get; set; }
        public string Customer_Last_Name { get; set; }
        public string Customer_Company_Name { get; set; }
        public Nullable<System.DateTime> Payment_Effective_Date { get; set; }
        public string Payment_Reference { get; set; }
        public string Payment_Source { get; set; }
        public string Payment_Type { get; set; }
        public string Payment_Method_Type { get; set; }
        public string Payment_Method { get; set; }
        public string Gateway { get; set; }
        public string Gateway_Reference { get; set; }
        public string Related_Payment_ID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Currency { get; set; }
        public long Payment_Transaction_ID { get; set; }
    }
}
