//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Charge : Transaction
    {
        public Charge()
        {
            this.Discounts = new HashSet<Discount>();
            this.Earnings = new HashSet<Earning>();
            this.ReverseCharges = new HashSet<ReverseCharge>();
            this.SubscriptionProductActivityJournalCharges = new HashSet<SubscriptionProductActivityJournalCharge>();
            this.Taxes = new HashSet<Tax>();
            this.ChargeProductItems = new HashSet<ChargeProductItem>();
        }
    
        public Nullable<long> InvoiceId { get; set; }
        public long DraftChargeId { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Quantity { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> ProratedUnitPrice { get; set; }
        public Nullable<decimal> RangeQuantity { get; set; }
        public decimal RemainingReverseAmount { get; set; }
        public long ChargeGroupId { get; set; }
        public System.DateTime EarningStartDate { get; set; }
        public System.DateTime EarningEndDate { get; set; }
        public EarningTimingType EarningTimingType { get; set; }
        public EarningTimingInterval EarningTimingInterval { get; set; }
    
        public virtual ChargeGroup ChargeGroup { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual ChargeLastEarning ChargeLastEarning { get; set; }
        public virtual ICollection<Discount> Discounts { get; set; }
        public virtual ICollection<Earning> Earnings { get; set; }
        public virtual ICollection<ReverseCharge> ReverseCharges { get; set; }
        public virtual ICollection<SubscriptionProductActivityJournalCharge> SubscriptionProductActivityJournalCharges { get; set; }
        public virtual SubscriptionProductCharge SubscriptionProductCharge { get; set; }
        public virtual ICollection<Tax> Taxes { get; set; }
        public virtual ICollection<ChargeProductItem> ChargeProductItems { get; set; }
        public virtual PurchaseCharge PurchaseCharge { get; set; }
    }
}
