//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargeLastEarning : Entity
    {
        public System.DateTime ModifiedTimestamp { get; set; }
        public Nullable<long> EarningId { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public Nullable<System.DateTime> EarningCompletedTimestamp { get; set; }
    
        public virtual Earning Earning { get; set; }
        public virtual Charge Charge { get; set; }
    }
}
