//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargeSummary : NullableEntity
    {
        public long AccountId { get; set; }
        public long CustomerId { get; set; }
        public Nullable<long> ProductId { get; set; }
        public string Status { get; set; }
        public System.DateTime EffectiveTimestamp { get; set; }
        public string ProductCode { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public Nullable<decimal> ProratedUnitPrice { get; set; }
        public decimal Amount { get; set; }
        public decimal RemainingReverseAmount { get; set; }
        public Nullable<long> DraftInvoiceId { get; set; }
        public Nullable<long> InvoiceId { get; set; }
        public Nullable<long> SubscriptionProductId { get; set; }
        public Nullable<long> PurchaseId { get; set; }
        public string RelatedPaymentNotes { get; set; }
        public string RelatedCreditNotes { get; set; }
        public string RelatedProductItems { get; set; }
    }
}
