//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country : Entity
    {
        public Country()
        {
            this.States = new HashSet<State>();
            this.Addresses = new HashSet<Address>();
            this.AccountBrandingPreferences = new HashSet<AccountBrandingPreference>();
            this.InvoiceAddresses = new HashSet<InvoiceAddress>();
            this.TaxRules = new HashSet<TaxRule>();
            this.PaymentMethods = new HashSet<PaymentMethod>();
            this.AvalaraConfiguration = new HashSet<AvalaraConfiguration>();
        }
    
        public string Name { get; set; }
        public string ISO { get; set; }
        public string ISO3 { get; set; }
    
        public virtual ICollection<State> States { get; set; }
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<AccountBrandingPreference> AccountBrandingPreferences { get; set; }
        public virtual ICollection<InvoiceAddress> InvoiceAddresses { get; set; }
        public virtual ICollection<TaxRule> TaxRules { get; set; }
        public virtual ICollection<PaymentMethod> PaymentMethods { get; set; }
        public virtual ICollection<AvalaraConfiguration> AvalaraConfiguration { get; set; }
    }
}
