//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponDiscount : Entity
    {
        public long CouponId { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.DateTime ModifiedTimestamp { get; set; }
        public long DiscountConfigurationId { get; set; }
        public Nullable<long> CouponEligibilityId { get; set; }
    
        public virtual Coupon Coupon { get; set; }
        public virtual DiscountConfiguration DiscountConfiguration { get; set; }
        public virtual CouponEligibility CouponEligibility { get; set; }
    }
}
