//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponPlan : Entity
    {
        public CouponPlan()
        {
            this.CouponPlanProduct = new HashSet<CouponPlanProduct>();
        }
    
        public long CouponId { get; set; }
        public long PlanId { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.DateTime ModifiedTimestamp { get; set; }
        public bool ApplyToAllProducts { get; set; }
    
        public virtual Coupon Coupon { get; set; }
        public virtual Plan Plan { get; set; }
        public virtual ICollection<CouponPlanProduct> CouponPlanProduct { get; set; }
    }
}
