//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponCode : Entity
    {
        public CouponCode()
        {
            this.SubscriptionCouponCodes = new HashSet<SubscriptionCouponCode>();
            this.SubscriptionProductDiscounts = new HashSet<SubscriptionProductDiscount>();
            this.PurchaseDiscounts = new HashSet<PurchaseDiscount>();
            this.PurchaseCouponCodes = new HashSet<PurchaseCouponCode>();
        }
    
        public long CouponId { get; set; }
        public string Code { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.DateTime ModifiedTimestamp { get; set; }
        public long AccountId { get; set; }
        public int TimesUsed { get; set; }
        public Nullable<int> RemainingUsages { get; set; }
    
        public virtual Coupon Coupon { get; set; }
        public virtual ICollection<SubscriptionCouponCode> SubscriptionCouponCodes { get; set; }
        public virtual ICollection<SubscriptionProductDiscount> SubscriptionProductDiscounts { get; set; }
        public virtual ICollection<PurchaseDiscount> PurchaseDiscounts { get; set; }
        public virtual ICollection<PurchaseCouponCode> PurchaseCouponCodes { get; set; }
    }
}
