//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    
    public enum CouponStatus : int
    {
        Draft = 1,
        Active = 2,
        Expired = 3,
        Retired = 4,
        Consumed = 5,
        Ineligible = 6,
    }
}
