//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon : Entity
    {
        public Coupon()
        {
            this.CouponCodes = new HashSet<CouponCode>();
            this.CouponDiscounts = new HashSet<CouponDiscount>();
            this.CouponPlans = new HashSet<CouponPlan>();
        }
    
        public string Name { get; set; }
        public string Description { get; set; }
        public CouponStatus Status { get; set; }
        public bool ApplyToAllPlans { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.DateTime ModifiedTimestamp { get; set; }
        public long AccountId { get; set; }
    
        public virtual ICollection<CouponCode> CouponCodes { get; set; }
        public virtual ICollection<CouponDiscount> CouponDiscounts { get; set; }
        public virtual ICollection<CouponPlan> CouponPlans { get; set; }
        public virtual Account Account { get; set; }
    }
}
