//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    
    public partial class CreditReport 
    {
        public long FusebillId { get; set; }
        public string CustomerId { get; set; }
        public Nullable<System.DateTime> EffectiveTimestamp { get; set; }
        public string CreditLineItemDescription { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
