//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credit : Transaction
    {
        public Credit()
        {
            this.CreditAllocations = new HashSet<CreditAllocation>();
            this.Debits = new HashSet<Debit>();
        }
    
        public string Reference { get; set; }
        public decimal UnallocatedAmount { get; set; }
        public decimal ReversableAmount { get; set; }
    
        public virtual ICollection<CreditAllocation> CreditAllocations { get; set; }
        public virtual ICollection<Debit> Debits { get; set; }
    }
}
