//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditNote : Entity
    {
        public CreditNote()
        {
            this.ReverseCharges = new HashSet<ReverseCharge>();
            this.ReverseTaxes = new HashSet<ReverseTax>();
            this.ReverseDiscounts = new HashSet<ReverseDiscount>();
        }
    
        public long InvoiceId { get; set; }
        public decimal Amount { get; set; }
    
        public virtual ICollection<ReverseCharge> ReverseCharges { get; set; }
        public virtual ICollection<ReverseTax> ReverseTaxes { get; set; }
        public virtual ICollection<ReverseDiscount> ReverseDiscounts { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
