//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency : Entity
    {
        public Currency()
        {
            this.AccountCurrencies = new HashSet<AccountCurrency>();
            this.LedgerEntries = new HashSet<LedgerEntry>();
            this.Prices = new HashSet<Price>();
            this.Transactions = new HashSet<Transaction>();
            this.PaymentActivityJournals = new HashSet<PaymentActivityJournal>();
            this.InvoiceCustomers = new HashSet<InvoiceCustomer>();
            this.Customers = new HashSet<Customer>();
            this.DraftCharge = new HashSet<DraftCharge>();
        }
    
        public string IsoName { get; set; }
        public string Symbol { get; set; }
    
        public virtual ICollection<AccountCurrency> AccountCurrencies { get; set; }
        public virtual ICollection<LedgerEntry> LedgerEntries { get; set; }
        public virtual ICollection<Price> Prices { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<PaymentActivityJournal> PaymentActivityJournals { get; set; }
        public virtual ICollection<InvoiceCustomer> InvoiceCustomers { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<DraftCharge> DraftCharge { get; set; }
    }
}
