//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer : Entity
    {
        public Customer()
        {
            this.BillingPeriods = new HashSet<BillingPeriod>();
            this.CollectionScheduleActivities = new HashSet<CollectionScheduleActivity>();
            this.CustomerAccountStatusJournals = new HashSet<CustomerAccountStatusJournal>();
            this.CustomerEmailPreferences = new HashSet<CustomerEmailPreference>();
            this.CustomerStatusJournals = new HashSet<CustomerStatusJournal>();
            this.CustomerEmailControls = new HashSet<CustomerEmailControl>();
            this.CustomerEmailLogs = new HashSet<CustomerEmailLog>();
            this.LedgerEntries = new HashSet<LedgerEntry>();
            this.PaymentActivityJournals = new HashSet<PaymentActivityJournal>();
            this.PaymentMethods = new HashSet<PaymentMethod>();
            this.Transactions = new HashSet<Transaction>();
            this.DraftInvoices = new HashSet<DraftInvoice>();
            this.Invoices = new HashSet<Invoice>();
            this.Subscriptions = new HashSet<Subscription>();
            this.BillingPeriodDefinitions = new HashSet<BillingPeriodDefinition>();
            this.CustomerNotes = new HashSet<CustomerNote>();
            this.SelfServicePortalToken = new HashSet<SelfServicePortalToken>();
            this.DraftCharges = new HashSet<DraftCharge>();
            this.FusebillSupportLogin = new HashSet<FusebillSupportLogin>();
            this.Purchase = new HashSet<Purchase>();
            this.AvalaraLog = new HashSet<AvalaraLog>();
            this.BillingStatement = new HashSet<BillingStatement>();
        }
    
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string PrimaryEmail { get; set; }
        public string PrimaryPhone { get; set; }
        public string SecondaryEmail { get; set; }
        public string SecondaryPhone { get; set; }
        public Nullable<Title> Title { get; set; }
        public string Reference { get; set; }
        public long AccountId { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.DateTime ModifiedTimestamp { get; set; }
        public System.DateTime EffectiveTimestamp { get; set; }
        public Nullable<System.DateTime> ActivationTimestamp { get; set; }
        public Nullable<System.DateTime> CancellationTimestamp { get; set; }
        public string CompanyName { get; set; }
        public long CurrencyId { get; set; }
        public decimal MonthlyRecurringRevenue { get; set; }
        public string SalesforceId { get; set; }
        public Nullable<byte> ActivationDay { get; set; }
        public decimal NetMRR { get; set; }
        public CustomerStatus Status { get; set; }
        public CustomerAccountStatus AccountStatus { get; set; }
        public string NetsuiteId { get; set; }
        public decimal ArBalance { get; set; }
        public Nullable<System.DateTime> NextBillingDate { get; set; }
        public Nullable<NetsuiteEntityType> NetsuiteEntityType { get; set; }
    
        public virtual ICollection<BillingPeriod> BillingPeriods { get; set; }
        public virtual ICollection<CollectionScheduleActivity> CollectionScheduleActivities { get; set; }
        public virtual ICollection<CustomerAccountStatusJournal> CustomerAccountStatusJournals { get; set; }
        public virtual CustomerAcquisition CustomerAcquisition { get; set; }
        public virtual CustomerAddressPreference CustomerAddressPreference { get; set; }
        public virtual CustomerBillingSetting CustomerBillingSetting { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual ICollection<CustomerEmailPreference> CustomerEmailPreferences { get; set; }
        public virtual CustomerReference CustomerReference { get; set; }
        public virtual CustomerStartingData CustomerStartingData { get; set; }
        public virtual ICollection<CustomerStatusJournal> CustomerStatusJournals { get; set; }
        public virtual ICollection<CustomerEmailControl> CustomerEmailControls { get; set; }
        public virtual ICollection<CustomerEmailLog> CustomerEmailLogs { get; set; }
        public virtual ICollection<LedgerEntry> LedgerEntries { get; set; }
        public virtual ICollection<PaymentActivityJournal> PaymentActivityJournals { get; set; }
        public virtual ICollection<PaymentMethod> PaymentMethods { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<DraftInvoice> DraftInvoices { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<Subscription> Subscriptions { get; set; }
        public virtual ICollection<BillingPeriodDefinition> BillingPeriodDefinitions { get; set; }
        public virtual ICollection<CustomerNote> CustomerNotes { get; set; }
        public virtual CustomerCredential CustomerCredential { get; set; }
        public virtual ICollection<SelfServicePortalToken> SelfServicePortalToken { get; set; }
        public virtual ICollection<DraftCharge> DraftCharges { get; set; }
        public virtual ICollection<FusebillSupportLogin> FusebillSupportLogin { get; set; }
        public virtual ICollection<Purchase> Purchase { get; set; }
        public virtual CustomerInvoiceSetting CustomerInvoiceSetting { get; set; }
        public virtual CustomerBillingStatementSetting CustomerBillingStatementSetting { get; set; }
        public virtual ICollection<AvalaraLog> AvalaraLog { get; set; }
        public virtual ICollection<BillingStatement> BillingStatement { get; set; }
    }
}
