//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerBillingSetting : Entity
    {
        public CustomerBillingSetting()
        {
            this.CustomerBillingPeriodConfigurations = new HashSet<CustomerBillingPeriodConfiguration>();
        }
    
        public System.DateTime CreatedTimestamp { get; set; }
        public System.DateTime ModifiedTimestamp { get; set; }
        public Nullable<int> InvoiceDay { get; set; }
        public Term Term { get; set; }
        public Interval Interval { get; set; }
        public Nullable<bool> AutoCollect { get; set; }
        public Nullable<bool> AutoPostDraftInvoice { get; set; }
        public Nullable<int> CustomerGracePeriod { get; set; }
        public Nullable<int> GracePeriodExtension { get; set; }
        public string StandingPo { get; set; }
        public decimal AcquisitionCost { get; set; }
        public Nullable<bool> ShowZeroDollarCharges { get; set; }
        public bool TaxExempt { get; set; }
        public string TaxExemptCode { get; set; }
        public Nullable<CustomerServiceStartOption> CustomerServiceStartOption { get; set; }
        public Nullable<RechargeType> RechargeType { get; set; }
        public Nullable<decimal> RechargeThresholdAmount { get; set; }
        public Nullable<decimal> RechargeTargetAmount { get; set; }
        public Nullable<bool> StatusOnThreshold { get; set; }
        public string AvalaraUsageType { get; set; }
        public string VATIdentificationNumber { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<CustomerBillingPeriodConfiguration> CustomerBillingPeriodConfigurations { get; set; }
    }
}
