//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOverview : Entity
    {
        public long AccountId { get; set; }
        public System.DateTime EffectiveTimestamp { get; set; }
        public string Reference { get; set; }
        public decimal PendingCharges { get; set; }
        public Nullable<decimal> ArBalance { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string CompanyName { get; set; }
        public string Suffix { get; set; }
        public Nullable<Title> Title { get; set; }
        public CustomerStatus CustomerStatus { get; set; }
        public string Currency { get; set; }
        public CustomerAccountStatus CustomerAccountStatus { get; set; }
        public Nullable<int> DaysUntilSuspension { get; set; }
        public System.DateTime AccountingStatusTimestamp { get; set; }
        public System.DateTime ServiceStatusTimestamp { get; set; }
        public Nullable<decimal> LifeTimeValue { get; set; }
        public decimal AvailableCredit { get; set; }
        public decimal MonthlyRecurringRevenue { get; set; }
        public decimal AvailableOpeningBalance { get; set; }
        public decimal AvailableFunds { get; set; }
        public Nullable<System.DateTime> NextBillingDate { get; set; }
        public decimal NetMRR { get; set; }
    }
}
