//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAddressPreference : Entity
    {
        public CustomerAddressPreference()
        {
            this.Addresses = new HashSet<Address>();
        }
    
        public string ContactName { get; set; }
        public string ShippingInstructions { get; set; }
        public bool UseBillingAddressAsShippingAddress { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.DateTime ModifiedTimestamp { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
