//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerReference : Entity
    {
        public string Reference1 { get; set; }
        public string Reference2 { get; set; }
        public string Reference3 { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.DateTime ModifiedTimestamp { get; set; }
        public Nullable<long> ClassicId { get; set; }
        public Nullable<long> SalesTrackingCode1Id { get; set; }
        public Nullable<long> SalesTrackingCode2Id { get; set; }
        public Nullable<long> SalesTrackingCode3Id { get; set; }
        public Nullable<long> SalesTrackingCode4Id { get; set; }
        public Nullable<long> SalesTrackingCode5Id { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual SalesTrackingCode SalesTrackingCode1 { get; set; }
        public virtual SalesTrackingCode SalesTrackingCode2 { get; set; }
        public virtual SalesTrackingCode SalesTrackingCode3 { get; set; }
        public virtual SalesTrackingCode SalesTrackingCode4 { get; set; }
        public virtual SalesTrackingCode SalesTrackingCode5 { get; set; }
    }
}
