//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInvoiceSetting : Entity
    {
        public Nullable<bool> RollUpTaxes { get; set; }
        public Nullable<bool> ShowTrackedItemName { get; set; }
        public Nullable<bool> ShowTrackedItemReference { get; set; }
        public Nullable<bool> ShowTrackedItemDescription { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
