//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerLedgerJournal : Entity
    {
        public System.DateTime CreatedTimestamp { get; set; }
        public long TransactionId { get; set; }
        public decimal ArDebit { get; set; }
        public decimal ArCredit { get; set; }
        public decimal CashDebit { get; set; }
        public decimal CashCredit { get; set; }
        public decimal UnearnedDebit { get; set; }
        public decimal UnearnedCredit { get; set; }
        public decimal EarnedDebit { get; set; }
        public decimal EarnedCredit { get; set; }
        public decimal WriteOffDebit { get; set; }
        public decimal WriteOffCredit { get; set; }
        public decimal TaxesPayableDebit { get; set; }
        public decimal TaxesPayableCredit { get; set; }
        public decimal DiscountDebit { get; set; }
        public decimal DiscountCredit { get; set; }
        public decimal OpeningBalanceDebit { get; set; }
        public decimal OpeningBalanceCredit { get; set; }
        public decimal CreditDebit { get; set; }
        public decimal CreditCredit { get; set; }
        public decimal UnearnedDiscountDebit { get; set; }
        public decimal UnearnedDiscountCredit { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
