//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAcquisition : Entity
    {
        public string AdContent { get; set; }
        public string Campaign { get; set; }
        public string Keyword { get; set; }
        public string LandingPage { get; set; }
        public string Medium { get; set; }
        public string Source { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.DateTime ModifiedTimestamp { get; set; }
        public string SystemSource { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
