//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerEmailLog : Entity
    {
        public CustomerEmailLog()
        {
            this.CustomerEmailLogInvoices = new HashSet<CustomerEmailLogInvoice>();
            this.CustomerEmailLogBillingStatement = new HashSet<CustomerEmailLogBillingStatement>();
        }
    
        public long CustomerId { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public bool AttachmentIncluded { get; set; }
        public Nullable<System.DateTime> EffectiveTimestamp { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public string ToEmail { get; set; }
        public string BccEmail { get; set; }
        public string ToDisplayName { get; set; }
        public string BccDisplayName { get; set; }
        public string FromEmail { get; set; }
        public string FromDisplayName { get; set; }
        public EmailStatus Status { get; set; }
        public string Result { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<CustomerEmailLogInvoice> CustomerEmailLogInvoices { get; set; }
        public virtual ICollection<CustomerEmailLogBillingStatement> CustomerEmailLogBillingStatement { get; set; }
    }
}
