//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerEmailLogBillingStatement : Entity
    {
        public long CustomerEmailLogId { get; set; }
        public long BillingStatementId { get; set; }
    
        public virtual CustomerEmailLog CustomerEmailLog { get; set; }
        public virtual BillingStatement BillingStatement { get; set; }
    }
}
