//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSummary : Entity
    {
        public string Reference { get; set; }
        public Nullable<Title> Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public decimal ArBalance { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public long AccountId { get; set; }
        public string PrimaryEmail { get; set; }
        public string PrimaryPhone { get; set; }
        public string SecondaryEmail { get; set; }
        public string SecondaryPhone { get; set; }
        public Nullable<System.DateTime> NextBillingDate { get; set; }
        public string CompanyName { get; set; }
        public CustomerStatus CustomerStatus { get; set; }
        public CustomerAccountStatus CustomerAccountStatus { get; set; }
        public string AccountingStatus { get; set; }
        public string Status { get; set; }
        public long CurrencyId { get; set; }
        public string Reference1 { get; set; }
        public string Reference2 { get; set; }
        public string Reference3 { get; set; }
        public string AdContent { get; set; }
        public string Campaign { get; set; }
        public string Keyword { get; set; }
        public string LandingPage { get; set; }
        public string Medium { get; set; }
        public string Source { get; set; }
        public Nullable<int> DaysUntilSuspension { get; set; }
        public string Terms { get; set; }
        public string PaymentMethod { get; set; }
        public decimal MonthlyRecurringRevenue { get; set; }
        public string SalesforceId { get; set; }
        public decimal NetMRR { get; set; }
        public string MaskedCardNumber { get; set; }
        public string NetsuiteId { get; set; }
        public Nullable<long> ClassicId { get; set; }
        public string SalesTrackingCode1Code { get; set; }
        public string SalesTrackingCode1Name { get; set; }
        public string SalesTrackingCode2Code { get; set; }
        public string SalesTrackingCode2Name { get; set; }
        public string SalesTrackingCode3Code { get; set; }
        public string SalesTrackingCode3Name { get; set; }
        public string SalesTrackingCode4Code { get; set; }
        public string SalesTrackingCode4Name { get; set; }
        public string SalesTrackingCode5Code { get; set; }
        public string SalesTrackingCode5Name { get; set; }
        public Nullable<long> SalesTrackingCode1Id { get; set; }
        public Nullable<long> SalesTrackingCode2Id { get; set; }
        public Nullable<long> SalesTrackingCode3Id { get; set; }
        public Nullable<long> SalesTrackingCode4Id { get; set; }
        public Nullable<long> SalesTrackingCode5Id { get; set; }
    }
}
