//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTransactionSummary : Entity
    {
        public long TransactionId { get; set; }
        public long CustomerId { get; set; }
        public long AccountId { get; set; }
        public System.DateTime EffectiveTimestamp { get; set; }
        public string TransactionType { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Reference { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public decimal ArDebit { get; set; }
        public decimal ArCredit { get; set; }
        public Nullable<long> AssociatedId { get; set; }
        public int AssociatedOrder { get; set; }
    }
}
