//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    
    public partial class CustomerInvoiceAge 
    {
        public string CustomerId { get; set; }
        public string CustomerStatus { get; set; }
        public Nullable<decimal> TotalAmountDue { get; set; }
        public decimal DueWithinTerms { get; set; }
        public decimal ZeroToThirtyDaysPastDue { get; set; }
        public decimal ThirtyOneToSixtyDaysPastDue { get; set; }
        public decimal SixtyOneToNinetyDaysPastDue { get; set; }
        public decimal NinetyOneToOneHundredTwentyDaysPastDue { get; set; }
        public decimal MoreThanOneHundredTwentyDaysPastDue { get; set; }
        public long FusebillId { get; set; }
        public string CustomerName { get; set; }
        public string CompanyName { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public decimal AvailableFunds { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
    }
}
