//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomField : Entity
    {
        public CustomField()
        {
            this.SubscriptionCustomFields = new HashSet<SubscriptionCustomField>();
            this.PlanFrequencyCustomFields = new HashSet<PlanFrequencyCustomField>();
            this.PlanProductFrequencyCustomFields = new HashSet<PlanProductFrequencyCustomField>();
            this.SubscriptionProductCustomFields = new HashSet<SubscriptionProductCustomField>();
            this.ProductCustomFields = new HashSet<ProductCustomField>();
            this.PurchaseCustomFields = new HashSet<PurchaseCustomField>();
        }
    
        public long AccountId { get; set; }
        public string FriendlyName { get; set; }
        public string Key { get; set; }
        public CustomFieldDataType DataType { get; set; }
        public CustomFieldStatus Status { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.DateTime ModifiedTimestamp { get; set; }
    
        public virtual ICollection<SubscriptionCustomField> SubscriptionCustomFields { get; set; }
        public virtual ICollection<PlanFrequencyCustomField> PlanFrequencyCustomFields { get; set; }
        public virtual ICollection<PlanProductFrequencyCustomField> PlanProductFrequencyCustomFields { get; set; }
        public virtual ICollection<SubscriptionProductCustomField> SubscriptionProductCustomFields { get; set; }
        public virtual ICollection<ProductCustomField> ProductCustomFields { get; set; }
        public virtual ICollection<PurchaseCustomField> PurchaseCustomFields { get; set; }
    }
}
