//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataWarehouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyAccountMrr
    {
        public Nullable<System.DateTime> FullDate { get; set; }
        public long AccountId { get; set; }
        public Nullable<decimal> NetMrr { get; set; }
        public Nullable<decimal> NewMrr { get; set; }
        public Nullable<decimal> ExpansionMrr { get; set; }
        public Nullable<decimal> LostMrr { get; set; }
        public Nullable<decimal> ContractionMrr { get; set; }
        public int CurrencyId { get; set; }
        public string IsLastDayOfMonth { get; set; }
    }
}
