//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debit : Transaction
    {
        public Debit()
        {
            this.DebitAllocations = new HashSet<DebitAllocation>();
        }
    
        public string Reference { get; set; }
        public long OriginalCreditId { get; set; }
    
        public virtual Credit Credit { get; set; }
        public virtual ICollection<DebitAllocation> DebitAllocations { get; set; }
    }
}
