//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount : Transaction
    {
        public Discount()
        {
            this.ReverseDiscounts = new HashSet<ReverseDiscount>();
            this.EarningDiscounts = new HashSet<EarningDiscount>();
        }
    
        public long ChargeId { get; set; }
        public decimal ConfiguredDiscountAmount { get; set; }
        public DiscountType DiscountType { get; set; }
        public decimal RemainingReversalAmount { get; set; }
        public decimal UnearnedAmount { get; set; }
        public decimal Quantity { get; set; }
    
        public virtual ICollection<ReverseDiscount> ReverseDiscounts { get; set; }
        public virtual Charge Charge { get; set; }
        public virtual ICollection<EarningDiscount> EarningDiscounts { get; set; }
    }
}
