//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountConfiguration : Entity
    {
        public DiscountConfiguration()
        {
            this.CouponDiscounts = new HashSet<CouponDiscount>();
        }
    
        public long AccountId { get; set; }
        public int RemainingUsagesUntilStart { get; set; }
        public Nullable<int> RemainingUsage { get; set; }
        public decimal Amount { get; set; }
        public DiscountType DiscountType { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public DiscountStatus Status { get; set; }
    
        public virtual ICollection<CouponDiscount> CouponDiscounts { get; set; }
    }
}
