//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DraftPaymentSchedule : Entity
    {
        public long DraftInvoiceId { get; set; }
        public decimal Amount { get; set; }
        public int DaysDueAfterTerm { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.DateTime ModifiedTimestamp { get; set; }
    
        public virtual DraftInvoice DraftInvoice { get; set; }
    }
}
