//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DraftInvoiceSummary : Entity
    {
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public decimal PendingCharges { get; set; }
        public long CustomerId { get; set; }
        public long AccountId { get; set; }
        public string Reference { get; set; }
        public long CurrencyId { get; set; }
        public DraftInvoiceStatus Status { get; set; }
    }
}
