//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DraftSubscriptionProductCharge : Entity
    {
        public long SubscriptionProductId { get; set; }
        public System.DateTime StartServiceDate { get; set; }
        public System.DateTime EndServiceDate { get; set; }
        public long BillingPeriodId { get; set; }
    
        public virtual DraftCharge DraftCharge { get; set; }
        public virtual SubscriptionProduct SubscriptionProduct { get; set; }
        public virtual BillingPeriod BillingPeriod { get; set; }
    }
}
