//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    
    public enum DraftInvoiceStatus : byte
    {
        Pending = 1,
        Ready = 2,
        Cancelled = 3,
        Deleted = 4,
    }
}
