//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DraftInvoice : Entity
    {
        public DraftInvoice()
        {
            this.DraftTaxes = new HashSet<DraftTax>();
            this.DraftPaymentSchedules = new HashSet<DraftPaymentSchedule>();
            this.DraftCharges = new HashSet<DraftCharge>();
        }
    
        public System.DateTime CreatedTimestamp { get; set; }
        public System.DateTime ModifiedTimestamp { get; set; }
        public Nullable<long> BillingPeriodId { get; set; }
        public Nullable<System.DateTime> EffectiveTimestamp { get; set; }
        public string PoNumber { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Total { get; set; }
        public long CustomerId { get; set; }
        public DraftInvoiceStatus DraftInvoiceStatus { get; set; }
        public Nullable<System.Guid> AvalaraId { get; set; }
        public string Notes { get; set; }
    
        public virtual BillingPeriod BillingPeriod { get; set; }
        public virtual ICollection<DraftTax> DraftTaxes { get; set; }
        public virtual ICollection<DraftPaymentSchedule> DraftPaymentSchedules { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<DraftCharge> DraftCharges { get; set; }
    }
}
