//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DraftDiscount : Entity
    {
        public decimal ConfiguredDiscountAmount { get; set; }
        public decimal Amount { get; set; }
        public long DraftChargeId { get; set; }
        public DiscountType DiscountType { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public Nullable<System.DateTime> EffectiveTimestamp { get; set; }
        public TransactionType TransactionType { get; set; }
        public string Description { get; set; }
        public long CurrencyId { get; set; }
        public decimal Quantity { get; set; }
    
        public virtual DraftCharge DraftCharge { get; set; }
    }
}
