//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DraftTax : Entity
    {
        public long TaxRuleId { get; set; }
        public long DraftInvoiceId { get; set; }
        public decimal Amount { get; set; }
        public long DraftChargeId { get; set; }
        public long CurrencyId { get; set; }
    
        public virtual TaxRule TaxRule { get; set; }
        public virtual DraftInvoice DraftInvoice { get; set; }
        public virtual DraftCharge DraftCharge { get; set; }
    }
}
