//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DraftCharge : Entity
    {
        public DraftCharge()
        {
            this.DraftDiscounts = new HashSet<DraftDiscount>();
            this.DraftTaxes = new HashSet<DraftTax>();
            this.SubscriptionProductActivityJournalDraftCharges = new HashSet<SubscriptionProductActivityJournalDraftCharge>();
            this.DraftChargeProductItems = new HashSet<DraftChargeProductItem>();
        }
    
        public System.DateTime CreatedTimestamp { get; set; }
        public System.DateTime ModifiedTimestamp { get; set; }
        public decimal Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Amount { get; set; }
        public Nullable<long> DraftInvoiceId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public TransactionType TransactionType { get; set; }
        public long CurrencyId { get; set; }
        public Nullable<System.DateTime> EffectiveTimestamp { get; set; }
        public Nullable<decimal> RangeQuantity { get; set; }
        public decimal TaxableAmount { get; set; }
        public DraftChargeStatus Status { get; set; }
        public byte SortOrder { get; set; }
        public long CustomerId { get; set; }
        public Nullable<decimal> ProratedUnitPrice { get; set; }
        public EarningTimingType EarningTimingType { get; set; }
        public EarningTimingInterval EarningTimingInterval { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual DraftInvoice DraftInvoice { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual ICollection<DraftDiscount> DraftDiscounts { get; set; }
        public virtual ICollection<DraftTax> DraftTaxes { get; set; }
        public virtual ICollection<SubscriptionProductActivityJournalDraftCharge> SubscriptionProductActivityJournalDraftCharges { get; set; }
        public virtual DraftSubscriptionProductCharge DraftSubscriptionProductCharge { get; set; }
        public virtual ICollection<DraftChargeProductItem> DraftChargeProductItems { get; set; }
        public virtual Purchase Purchase { get; set; }
    }
}
