//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Earning : Transaction
    {
        public Earning()
        {
            this.ChargeLastEarnings = new HashSet<ChargeLastEarning>();
        }
    
        public long ChargeId { get; set; }
        public string Reference { get; set; }
    
        public virtual ICollection<ChargeLastEarning> ChargeLastEarnings { get; set; }
        public virtual Charge Charge { get; set; }
    }
}
