//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    
    public enum EmailTemplateType : int
    {
        InvoicePost = 1,
        PaymentReceived = 2,
        InvoiceOverdue = 3,
        PasswordReset = 4,
        PasswordSetup = 5,
        PaymentFailed = 6,
        CustomerActivation = 7,
        SubscriptionActivation = 8,
        SubscriptionCancellation = 9,
        CustomerCredentialCreate = 10,
        CustomerCredentialPasswordReset = 11,
        CustomerSuspend = 12,
        PaymentMethodUpdate = 13,
        CreditCardExpiry = 14,
        BillingStatementNotification = 15,
    }
}
