//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    
    public enum EntityType : int
    {
        Account = 1,
        User = 2,
        Customer = 3,
        Plan = 4,
        CustomerAddressPreference = 5,
        Address = 6,
        Subscription = 7,
        AccountPreference = 8,
        CustomerBillingSetting = 9,
        DraftInvoice = 10,
        Invoice = 11,
        Product = 12,
        Gateway = 13,
        SubscriptionProduct = 14,
    }
}
