//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FusebillSupportLogin : Entity
    {
        public System.Guid Token { get; set; }
        public long UserId { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public bool Consumed { get; set; }
        public long AccountId { get; set; }
        public Nullable<long> CustomerId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual User User { get; set; }
    }
}
