//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FusebillField : Entity
    {
        public FusebillField()
        {
            this.AccountNetsuiteFieldMapping = new HashSet<AccountNetsuiteFieldMapping>();
        }
    
        public string Name { get; set; }
        public string PropertyName { get; set; }
    
        public virtual ICollection<AccountNetsuiteFieldMapping> AccountNetsuiteFieldMapping { get; set; }
    }
}
