//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    
    public partial class FusebillLoginSession 
    {
        public Nullable<long> AccountId { get; set; }
        public Nullable<long> UserId { get; set; }
        public string UserEmail { get; set; }
        public Nullable<long> CustomerId { get; set; }
    }
}
