//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HostedPageSelfServicePortal : HostedPage
    {
        public string UnauthenticatedHeader { get; set; }
        public string LoginLabel { get; set; }
        public string Home { get; set; }
        public bool EnableStatements { get; set; }
    }
}
