//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HostedPageRegistration : HostedPage
    {
        public string SuccessUrl { get; set; }
        public string FailureUrl { get; set; }
        public string CustomerInformation { get; set; }
        public string PlanList { get; set; }
        public string PaymentMethod { get; set; }
        public string InvoicePreview { get; set; }
        public bool AllowCoupons { get; set; }
        public Nullable<long> SalesTrackingCode1Id { get; set; }
        public Nullable<long> SalesTrackingCode2Id { get; set; }
        public Nullable<long> SalesTrackingCode3Id { get; set; }
        public Nullable<long> SalesTrackingCode4Id { get; set; }
        public Nullable<long> SalesTrackingCode5Id { get; set; }
        public bool UseLegacyView { get; set; }
        public bool ShowTermsAndConditions { get; set; }
        public string TermsCheckboxLabel { get; set; }
        public string TermsLink { get; set; }
        public string TermsLinkText { get; set; }
    
        public virtual SalesTrackingCode SalesTrackingCode1 { get; set; }
        public virtual SalesTrackingCode SalesTrackingCode2 { get; set; }
        public virtual SalesTrackingCode SalesTrackingCode3 { get; set; }
        public virtual SalesTrackingCode SalesTrackingCode4 { get; set; }
        public virtual SalesTrackingCode SalesTrackingCode5 { get; set; }
    }
}
