//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HostedPage : Entity
    {
        public long AccountId { get; set; }
        public HostedPageType HostedPageType { get; set; }
        public string FriendlyName { get; set; }
        public HostedPageDomain HostedPageDomain { get; set; }
        public string Key { get; set; }
        public HostedPageStatus HostedPageStatus { get; set; }
        public string Header { get; set; }
        public string SubHeader { get; set; }
        public string Footer { get; set; }
        public string PreFooter { get; set; }
        public string CSS { get; set; }
        public string Menu { get; set; }
        public string GoogleAnalytics { get; set; }
        public int Version { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
