//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    
    public enum IntegrationSyncBatchStatus : int
    {
        NotSent = 1,
        Queued = 2,
        InProgress = 3,
        Completed = 4,
        Failure = 5,
    }
}
