//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationSyncBatchRecord : Entity
    {
        public long IntegrationSyncBatchId { get; set; }
        public EntityType EntityType { get; set; }
        public long EntityId { get; set; }
        public string ExternalId { get; set; }
        public Nullable<IntegrationSyncBatchRecordStatus> Status { get; set; }
        public string FailureReason { get; set; }
    
        public virtual IntegrationSyncBatch IntegrationSyncBatch { get; set; }
    }
}
