//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationSyncSubscriptionData : Entity
    {
        public long BatchId { get; set; }
        public string SalesforceId { get; set; }
        public string AccountSalesforceId { get; set; }
        public string NetsuiteId { get; set; }
        public string CustomerNetsuiteId { get; set; }
        public Nullable<System.DateTime> ActivationTimestamp { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public long CustomerId { get; set; }
        public string Frequency { get; set; }
        public decimal MonthlyRecurringRevenue { get; set; }
        public Nullable<System.DateTime> NextPeriodStartDate { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public string SubscriptionName { get; set; }
        public Nullable<System.DateTime> ProvisionedTimestamp { get; set; }
        public string Reference { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ScheduledActivationTimestamp { get; set; }
        public Nullable<int> RemainingInterval { get; set; }
        public long AccountId { get; set; }
    }
}
