//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationSyncBatch : Entity
    {
        public IntegrationSyncBatch()
        {
            this.IntegrationSyncBatchRecords = new HashSet<IntegrationSyncBatchRecord>();
        }
    
        public string ExternalBatchId { get; set; }
        public long IntegrationSyncJobId { get; set; }
        public Nullable<IntegrationSyncBatchStatus> Status { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.DateTime ModifiedTimestamp { get; set; }
        public int RecordsToProcess { get; set; }
        public Nullable<System.DateTime> LastPolledTimestamp { get; set; }
    
        public virtual IntegrationSyncJob IntegrationSyncJob { get; set; }
        public virtual ICollection<IntegrationSyncBatchRecord> IntegrationSyncBatchRecords { get; set; }
    }
}
