//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    
    public enum IntegrationSyncJobRequestStatus : int
    {
        Sent = 1,
        ReadyToSend = 2,
        Pending = 3,
        WillNotSend = 4,
    }
}
