//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationSyncCustomerData : Entity
    {
        public long BatchId { get; set; }
        public Nullable<int> InvoiceDay { get; set; }
        public Nullable<int> GracePeriod { get; set; }
        public string Currency { get; set; }
        public string SalesforceId { get; set; }
        public string NetsuiteId { get; set; }
        public string Reference { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public long AccountId { get; set; }
        public string PrimaryEmail { get; set; }
        public string PrimaryPhone { get; set; }
        public string SecondaryEmail { get; set; }
        public string SecondaryPhone { get; set; }
        public string AccountName { get; set; }
        public string CompanyName { get; set; }
        public string AccountStatus { get; set; }
        public string AccountingStatus { get; set; }
        public string Status { get; set; }
        public string Reference1 { get; set; }
        public string Reference2 { get; set; }
        public string Reference3 { get; set; }
        public string AdContent { get; set; }
        public string Campaign { get; set; }
        public string Keyword { get; set; }
        public string LandingPage { get; set; }
        public string Medium { get; set; }
        public string Source { get; set; }
        public string Terms { get; set; }
        public decimal MonthlyRecurringRevenue { get; set; }
        public string AutoCollect { get; set; }
    }
}
