//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    
    public enum IntegrationSyncJobResponseStatus : int
    {
        NotSent = 1,
        InProgress = 2,
        Success = 3,
        Failure = 4,
    }
}
