//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationSyncInvoiceData : Entity
    {
        public long BatchId { get; set; }
        public string SalesforceId { get; set; }
        public string AccountSalesforceId { get; set; }
        public Nullable<int> NetsuiteId { get; set; }
        public string CustomerNetsuiteId { get; set; }
        public int InvoiceNumber { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public System.DateTime PostedTimestamp { get; set; }
        public decimal SumOfCharges { get; set; }
        public decimal OutstandingBalance { get; set; }
        public decimal TotalPayments { get; set; }
        public decimal SumOfCreditNotes { get; set; }
        public decimal Amount { get; set; }
        public decimal TotalWriteoffs { get; set; }
        public string Status { get; set; }
        public Nullable<long> Installments { get; set; }
        public long AccountId { get; set; }
        public string InvoiceName { get; set; }
    }
}
