//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationSyncJob : Entity
    {
        public IntegrationSyncJob()
        {
            this.IntegrationSyncBatches = new HashSet<IntegrationSyncBatch>();
            this.IntegrationSyncJobChildren = new HashSet<IntegrationSyncJob>();
        }
    
        public long AccountId { get; set; }
        public string ApiVersion { get; set; }
        public string ExternalJobId { get; set; }
        public EntityType EntityType { get; set; }
        public Nullable<System.DateTime> StartTimestamp { get; set; }
        public IntegrationSyncJobRequestStatus RequestStatus { get; set; }
        public Nullable<IntegrationSyncJobResponseStatus> ResponseStatus { get; set; }
        public Nullable<long> ParentJobId { get; set; }
        public Nullable<System.DateTime> LastPolledTimestamp { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.DateTime ModifiedTimestamp { get; set; }
        public string Operation { get; set; }
        public IntegrationType IntegrationType { get; set; }
    
        public virtual ICollection<IntegrationSyncBatch> IntegrationSyncBatches { get; set; }
        public virtual ICollection<IntegrationSyncJob> IntegrationSyncJobChildren { get; set; }
        public virtual IntegrationSyncJob IntegrationSyncJobParent { get; set; }
    }
}
