//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationSyncSubscriptionProductData : Entity
    {
        public long BatchId { get; set; }
        public string SalesforceId { get; set; }
        public string SubscriptionSalesforceId { get; set; }
        public string AccountSalesforceId { get; set; }
        public string NetsuiteId { get; set; }
        public string SubscriptionNetsuiteId { get; set; }
        public string CustomerNetsuiteId { get; set; }
        public decimal Amount { get; set; }
        public string IsIncluded { get; set; }
        public string IsRecurring { get; set; }
        public string IsTrackingItems { get; set; }
        public decimal MonthlyRecurringRevenue { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public string ProductName { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public long SubscriptionId { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public long AccountId { get; set; }
    }
}
