//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceJournal : Entity
    {
        public long InvoiceId { get; set; }
        public decimal SumOfCharges { get; set; }
        public decimal SumOfPayments { get; set; }
        public decimal SumOfRefunds { get; set; }
        public decimal SumOfCreditNotes { get; set; }
        public decimal SumOfWriteOffs { get; set; }
        public decimal OutstandingBalance { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public decimal SumOfTaxes { get; set; }
        public decimal SumOfDiscounts { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
