//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice : Entity
    {
        public Invoice()
        {
            this.CreditAllocations = new HashSet<CreditAllocation>();
            this.CreditNotes = new HashSet<CreditNote>();
            this.DebitAllocations = new HashSet<DebitAllocation>();
            this.Disputes = new HashSet<Dispute>();
            this.InvoiceAddresses = new HashSet<InvoiceAddress>();
            this.InvoiceJournals = new HashSet<InvoiceJournal>();
            this.OpeningBalanceAllocations = new HashSet<OpeningBalanceAllocation>();
            this.PaymentNotes = new HashSet<PaymentNote>();
            this.PaymentSchedules = new HashSet<PaymentSchedule>();
            this.RefundNotes = new HashSet<RefundNote>();
            this.Taxes = new HashSet<Tax>();
            this.WriteOffs = new HashSet<WriteOff>();
            this.CustomerEmailLogInvoices = new HashSet<CustomerEmailLogInvoice>();
            this.ChargeGroups = new HashSet<ChargeGroup>();
            this.Charges = new HashSet<Charge>();
            this.AvalaraLog = new HashSet<AvalaraLog>();
        }
    
        public long AccountId { get; set; }
        public int InvoiceNumber { get; set; }
        public Nullable<long> BillingPeriodId { get; set; }
        public long DraftInvoiceId { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.DateTime PostedTimestamp { get; set; }
        public System.DateTime EffectiveTimestamp { get; set; }
        public string Signature { get; set; }
        public string PoNumber { get; set; }
        public string SalesforceId { get; set; }
        public long CustomerId { get; set; }
        public Nullable<System.Guid> AvalaraId { get; set; }
        public string Notes { get; set; }
    
        public virtual BillingPeriod BillingPeriod { get; set; }
        public virtual ICollection<CreditAllocation> CreditAllocations { get; set; }
        public virtual ICollection<CreditNote> CreditNotes { get; set; }
        public virtual ICollection<DebitAllocation> DebitAllocations { get; set; }
        public virtual ICollection<Dispute> Disputes { get; set; }
        public virtual ICollection<InvoiceAddress> InvoiceAddresses { get; set; }
        public virtual InvoiceCustomer InvoiceCustomer { get; set; }
        public virtual ICollection<InvoiceJournal> InvoiceJournals { get; set; }
        public virtual ICollection<OpeningBalanceAllocation> OpeningBalanceAllocations { get; set; }
        public virtual ICollection<PaymentNote> PaymentNotes { get; set; }
        public virtual ICollection<PaymentSchedule> PaymentSchedules { get; set; }
        public virtual ICollection<RefundNote> RefundNotes { get; set; }
        public virtual ICollection<Tax> Taxes { get; set; }
        public virtual ICollection<WriteOff> WriteOffs { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<CustomerEmailLogInvoice> CustomerEmailLogInvoices { get; set; }
        public virtual ICollection<ChargeGroup> ChargeGroups { get; set; }
        public virtual ICollection<Charge> Charges { get; set; }
        public virtual ICollection<AvalaraLog> AvalaraLog { get; set; }
    }
}
