//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    
    public enum InvoiceStatus : int
    {
        Pending = 1,
        Due = 2,
        Overdue = 3,
        Paid = 4,
        WrittenOff = 5,
        Disputed = 6,
    }
}
