//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LedgerEntry : Entity
    {
        public LedgerType LedgerType { get; set; }
        public long TransactionId { get; set; }
        public long CustomerId { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public long CurrencyId { get; set; }
    
        public virtual Transaction Transaction { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
