//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    
    public enum LedgerType : int
    {
        ARBalance = 1,
        CashCollected = 2,
        EarnedRevenue = 3,
        DeferredRevenue = 4,
        TaxesPayable = 5,
        Discount = 6,
        WriteOff = 7,
        OpeningBalance = 8,
        Credit = 9,
        DeferredDiscount = 10,
    }
}
