//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpeningBalance : Transaction
    {
        public OpeningBalance()
        {
            this.OpeningBalanceAllocations = new HashSet<OpeningBalanceAllocation>();
        }
    
        public string Reference { get; set; }
        public decimal UnallocatedAmount { get; set; }
    
        public virtual ICollection<OpeningBalanceAllocation> OpeningBalanceAllocations { get; set; }
    }
}
