//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderToCashCycle : Entity
    {
        public OrderToCashCycle()
        {
            this.QuantityRanges = new HashSet<QuantityRange>();
            this.Product = new HashSet<Product>();
        }
    
        public System.DateTime CreatedTimestamp { get; set; }
        public System.DateTime ModifiedTimestamp { get; set; }
        public PricingModelType PricingModelType { get; set; }
        public bool IsEarnedImmediately { get; set; }
        public Nullable<Interval> EarningInterval { get; set; }
        public Nullable<int> EarningNumberOfInterval { get; set; }
        public EarningTimingType EarningTimingType { get; set; }
        public EarningTimingInterval EarningTimingInterval { get; set; }
    
        public virtual ICollection<QuantityRange> QuantityRanges { get; set; }
        public virtual ICollection<Product> Product { get; set; }
    }
}
