//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    
    public partial class OverdueInvoice 
    {
        public long Id { get; set; }
        public int DaysFromTerm { get; set; }
        public long PaymentScheduleId { get; set; }
        public long AccountId { get; set; }
        public System.DateTime UtcPeriodEndDateTime { get; set; }
    }
}
