//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentActivityJournal : Entity
    {
        public PaymentActivityJournal()
        {
            this.Payments = new HashSet<Payment>();
            this.Refunds = new HashSet<Refund>();
        }
    
        public long CustomerId { get; set; }
        public decimal Amount { get; set; }
        public string AuthorizationCode { get; set; }
        public PaymentSource PaymentSource { get; set; }
        public PaymentActivityStatus PaymentActivityStatus { get; set; }
        public PaymentType PaymentType { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.DateTime ModifiedTimestamp { get; set; }
        public System.DateTime EffectiveTimestamp { get; set; }
        public string AuthorizationResponse { get; set; }
        public PaymentMethodType PaymentMethodType { get; set; }
        public long CurrencyId { get; set; }
        public string PaymentPlatformCode { get; set; }
        public Nullable<long> GatewayId { get; set; }
        public string GatewayName { get; set; }
        public Nullable<long> PaymentMethodId { get; set; }
        public string SecondaryTransactionNumber { get; set; }
    
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual ICollection<Refund> Refunds { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
