//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentSchedule : Entity
    {
        public PaymentSchedule()
        {
            this.PaymentScheduleJournals = new HashSet<PaymentScheduleJournal>();
        }
    
        public long InvoiceId { get; set; }
        public decimal Amount { get; set; }
        public int DaysDueAfterTerm { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public bool IsDefault { get; set; }
    
        public virtual ICollection<PaymentScheduleJournal> PaymentScheduleJournals { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
