//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment : Transaction
    {
        public Payment()
        {
            this.PaymentNotes = new HashSet<PaymentNote>();
            this.Refunds = new HashSet<Refund>();
        }
    
        public string Reference { get; set; }
        public long PaymentActivityJournalId { get; set; }
        public decimal RefundableAmount { get; set; }
        public decimal UnallocatedAmount { get; set; }
    
        public virtual ICollection<PaymentNote> PaymentNotes { get; set; }
        public virtual ICollection<Refund> Refunds { get; set; }
        public virtual PaymentActivityJournal PaymentActivityJournal { get; set; }
    }
}
