//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentNote : Entity
    {
        public System.DateTime CreatedTimestamp { get; set; }
        public long InvoiceId { get; set; }
        public long PaymentId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime EffectiveTimestamp { get; set; }
    
        public virtual Payment Payment { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
