//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanProductKey : Entity
    {
        public PlanProductKey()
        {
            this.PlanProducts = new HashSet<PlanProduct>();
            this.PlanProductFrequencyCustomFields = new HashSet<PlanProductFrequencyCustomField>();
            this.CouponPlanProduct = new HashSet<CouponPlanProduct>();
        }
    
        public System.DateTime CreatedTimestamp { get; set; }
    
        public virtual ICollection<PlanProduct> PlanProducts { get; set; }
        public virtual ICollection<PlanProductFrequencyCustomField> PlanProductFrequencyCustomFields { get; set; }
        public virtual ICollection<CouponPlanProduct> CouponPlanProduct { get; set; }
    }
}
