//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanFrequencyKey : Entity
    {
        public PlanFrequencyKey()
        {
            this.PlanFrequencies = new HashSet<PlanFrequency>();
            this.PlanFrequencyCustomFields = new HashSet<PlanFrequencyCustomField>();
            this.PlanProductFrequencyCustomFields = new HashSet<PlanProductFrequencyCustomField>();
        }
    
        public System.DateTime CreatedTimestamp { get; set; }
    
        public virtual ICollection<PlanFrequency> PlanFrequencies { get; set; }
        public virtual ICollection<PlanFrequencyCustomField> PlanFrequencyCustomFields { get; set; }
        public virtual ICollection<PlanProductFrequencyCustomField> PlanProductFrequencyCustomFields { get; set; }
    }
}
