//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanProductFrequencyCustomField : Entity
    {
        public long PlanProductUniqueId { get; set; }
        public long PlanFrequencyUniqueId { get; set; }
        public long CustomFieldId { get; set; }
        public string DefaultStringValue { get; set; }
        public Nullable<System.DateTime> DefaultDateValue { get; set; }
        public Nullable<decimal> DefaultNumericValue { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.DateTime ModifiedTimestamp { get; set; }
    
        public virtual CustomField CustomField { get; set; }
        public virtual PlanFrequencyKey PlanFrequencyKey { get; set; }
        public virtual PlanProductKey PlanProductKey { get; set; }
    }
}
