//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanSummary : Entity
    {
        public long AccountId { get; set; }
        public string PlanCode { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public PlanStatus PlanStatus { get; set; }
        public int Subscriptions { get; set; }
        public long PlanRevisionId { get; set; }
        public string Reference { get; set; }
    }
}
