//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan : Entity
    {
        public Plan()
        {
            this.PlanRevisions = new HashSet<PlanRevision>();
            this.CouponPlans = new HashSet<CouponPlan>();
        }
    
        public long AccountId { get; set; }
        public System.DateTime ModifiedTimestamp { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public PlanStatus Status { get; set; }
        public string LongDescription { get; set; }
        public string Reference { get; set; }
        public bool AutoApplyChanges { get; set; }
    
        public virtual ICollection<PlanRevision> PlanRevisions { get; set; }
        public virtual ICollection<CouponPlan> CouponPlans { get; set; }
    }
}
