//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanProduct : Entity
    {
        public PlanProduct()
        {
            this.SubscriptionProducts = new HashSet<SubscriptionProduct>();
            this.PlanOrderToCashCycles = new HashSet<PlanOrderToCashCycle>();
        }
    
        public long ProductId { get; set; }
        public long PlanRevisionId { get; set; }
        public bool IsOptional { get; set; }
        public bool IsIncludedByDefault { get; set; }
        public bool IsFixed { get; set; }
        public bool IsRecurring { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<decimal> MaxQuantity { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.DateTime ModifiedTimestamp { get; set; }
        public bool IsTrackingItems { get; set; }
        public ProductResetType ResetType { get; set; }
        public Nullable<long> PlanProductUniqueId { get; set; }
        public PlanProductStatus Status { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public bool ChargeAtSubscriptionActivation { get; set; }
    
        public virtual PlanRevision PlanRevision { get; set; }
        public virtual Product Product { get; set; }
        public virtual PlanProductKey PlanProductKey { get; set; }
        public virtual ICollection<SubscriptionProduct> SubscriptionProducts { get; set; }
        public virtual ICollection<PlanOrderToCashCycle> PlanOrderToCashCycles { get; set; }
    }
}
