//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanFrequency : Entity
    {
        public PlanFrequency()
        {
            this.Subscriptions = new HashSet<Subscription>();
            this.PlanOrderToCashCycles = new HashSet<PlanOrderToCashCycle>();
        }
    
        public long PlanRevisionId { get; set; }
        public int NumberOfIntervals { get; set; }
        public Interval Interval { get; set; }
        public PlanFrequencyStatus Status { get; set; }
        public long PlanFrequencyUniqueId { get; set; }
        public int NumberOfSubscriptions { get; set; }
    
        public virtual PlanRevision PlanRevision { get; set; }
        public virtual PlanFrequencyKey PlanFrequencyKey { get; set; }
        public virtual ICollection<Subscription> Subscriptions { get; set; }
        public virtual ICollection<PlanOrderToCashCycle> PlanOrderToCashCycles { get; set; }
    }
}
