//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanOrderToCashCycle : OrderToCashCycle
    {
        public long PlanProductId { get; set; }
        public long PlanFrequencyId { get; set; }
        public ChargeTimingType RecurChargeTimingType { get; set; }
        public Nullable<ProrateGranularity> RecurProrateGranularity { get; set; }
        public bool RecurProrateNegativeQuantity { get; set; }
        public bool RecurProratePositiveQuantity { get; set; }
        public bool RecurReverseChargeNegativeQuantity { get; set; }
        public ChargeTimingType QuantityChargeTimingType { get; set; }
        public Nullable<ProrateGranularity> QuantityProrateGranularity { get; set; }
        public bool QuantityProrateNegativeQuantity { get; set; }
        public bool QuantityProratePositiveQuantity { get; set; }
        public bool QuantityReverseChargeNegativeQuantity { get; set; }
    
        public virtual PlanFrequency PlanFrequency { get; set; }
        public virtual PlanProduct PlanProduct { get; set; }
    }
}
