//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price : Entity
    {
        public long QuantityRangeId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public long CurrencyId { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual QuantityRange QuantityRange { get; set; }
    }
}
