//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PricingModelOverride : Entity
    {
        public PricingModelOverride()
        {
            this.PriceRangeOverrides = new HashSet<PriceRangeOverride>();
        }
    
        public System.DateTime CreatedTimestamp { get; set; }
        public System.DateTime ModifiedTimestamp { get; set; }
        public PricingModelType PricingModelType { get; set; }
    
        public virtual ICollection<PriceRangeOverride> PriceRangeOverrides { get; set; }
        public virtual SubscriptionProduct SubscriptionProduct { get; set; }
    }
}
