//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    
    public enum ProductType : int
    {
        PhysicalGood = 1,
        RecurringService = 2,
        OneTimeCharge = 3,
        PlanSetupFee = 4,
        PlanCharge = 5,
    }
}
