//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductItem : Entity
    {
        public ProductItem()
        {
            this.ChargeProductItems = new HashSet<ChargeProductItem>();
            this.DraftChargeProductItems = new HashSet<DraftChargeProductItem>();
        }
    
        public System.DateTime CreatedTimestamp { get; set; }
        public string Reference { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime ModifiedTimestamp { get; set; }
        public long ProductId { get; set; }
        public SubscriptionProductItemStatus Status { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ICollection<ChargeProductItem> ChargeProductItems { get; set; }
        public virtual ICollection<DraftChargeProductItem> DraftChargeProductItems { get; set; }
        public virtual SubscriptionProduct SubscriptionProduct { get; set; }
        public virtual Purchase Purchase { get; set; }
    }
}
