//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product : Entity
    {
        public Product()
        {
            this.PlanProducts = new HashSet<PlanProduct>();
            this.ProductCustomFields = new HashSet<ProductCustomField>();
            this.ProductItem = new HashSet<ProductItem>();
            this.Purchase = new HashSet<Purchase>();
        }
    
        public System.DateTime CreatedTimestamp { get; set; }
        public System.DateTime ModifiedTimestamp { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public ProductType ProductType { get; set; }
        public long AccountId { get; set; }
        public ProductStatus Status { get; set; }
        public bool TaxExempt { get; set; }
        public bool AvailableForPurchase { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<long> OrderToCashCycleId { get; set; }
        public bool IsTrackingItems { get; set; }
        public string AvalaraItemCode { get; set; }
        public string AvalaraTaxCode { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<PlanProduct> PlanProducts { get; set; }
        public virtual OrderToCashCycle OrderToCashCycle { get; set; }
        public virtual ICollection<ProductCustomField> ProductCustomFields { get; set; }
        public virtual ICollection<ProductItem> ProductItem { get; set; }
        public virtual ICollection<Purchase> Purchase { get; set; }
    }
}
