//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseCouponCode : Entity
    {
        public long PurchaseId { get; set; }
        public long CouponCodeId { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
    
        public virtual CouponCode CouponCode { get; set; }
        public virtual Purchase Purchase { get; set; }
    }
}
